Corrected: Fix for "Too many files open" bug
kentcdodds/split-guide pull request #16
Opened 2017-02-15 22:35 UTC by raygesualdo

The error raised in #3 occurs when there's a lot of files that `split-guide` has to read. I found the number for small files to be somewhere between 1000 and 10,000 (the number changes based on system resources available and file size). To solve this, I wrote a utility function that takes all of the files that need to be opened, chunks them out into smaller groups, runs `Promise.all` on each of the chunks serially, then returns the whole set. I've tested this with an exercise set of 10,000 files and it works great. I tried 100,000 files and Node completely crashed on me with an out of memory exception, but hopefully no one will ever use this with that many files :)

2017-02-15 23:13 UTC, kentcdodds approved these changes
Looks pretty awesome. Just a few questions, but I don't think we need to change anything!

2017-02-15 23:13 UTC, kentcdodds commented on src/index.js
> +  function promiseChunker(remainingArrayElements, chunkSize) {
Hey, this is a pretty nifty function!

2017-02-15 23:13 UTC, kentcdodds commented on src/index.js
> +    .then(reduceFilenames)
What was the purpose of adding this? I don't think I mind it, but I'm curious why you added it :)

2017-02-15 23:13 UTC, kentcdodds commented on src/index.js
> +    ].filter(p => !!p) // filter out the files that weren't saved
Any reason this was changed from `].filter(Boolean)`?

2017-02-15 23:15 UTC, kentcdodds commented on src/index.js
> +    if (remainingArrayElements.length === 0) return Promise.resolve([])
Oh, linting is failing because I prefer to put if statements in blocks.

2017-02-15 23:15 UTC, kentcdodds requested changes
Let's fix linting really quick, then I think we're good :)

2017-02-16 00:13 UTC, raygesualdo commented on src/index.js
> +  function promiseChunker(remainingArrayElements, chunkSize) {
Thanks! It took me a bit to come up with what's here, but I'm pleased with how it turned out.

2017-02-16 00:13 UTC, raygesualdo commented on src/index.js
> +    if (remainingArrayElements.length === 0) return Promise.resolve([])
Oops, I'll get that taken care of.

2017-02-16 00:14 UTC, raygesualdo commented on src/index.js
> +    ].filter(p => !!p) // filter out the files that weren't saved
No. I think that was an error when I updated my branch with the latest from your repo. I'll revert it.

2017-02-16 00:17 UTC, kentcdodds commented on src/index.js
> +  function promiseChunker(remainingArrayElements, chunkSize) {
Actually, I know that sindre sorhus came up with a [bunch of promise related modules](https://github.com/sindresorhus/promise-fun) recently. Maybe he's got a utility like this...

2017-02-16 00:18 UTC, kentcdodds commented on src/index.js
> +  function promiseChunker(remainingArrayElements, chunkSize) {
Maybe this one? https://github.com/sindresorhus/p-limit

2017-02-16 00:22 UTC, raygesualdo commented on src/index.js
> +  function promiseChunker(remainingArrayElements, chunkSize) {
That would also work. Would you like me to swap it out?

2017-02-16 00:27 UTC, kentcdodds commented on src/index.js
> +  function promiseChunker(remainingArrayElements, chunkSize) {
Yeah, it's good to use well tested modules I think. Sorry!

2017-02-16 00:40 UTC, raygesualdo commented
Made the changes you requested. The `p-limit` package was a good call. Cleaned up the PR considerably.

2017-02-16 01:22 UTC, kentcdodds approved these changes
Super!

2017-02-16 01:22 UTC, merged